In [1]:
from sklearn.preprocessing import StandardScaler 
from pandas import read_csv 
from numpy import set_printoptions 


In [7]:
path = r"diabetes.csv"
headers = ['preg','plas','skin','test','mass','pedi','age','class']
dataframe = read_csv(path,names=headers)
array = dataframe.values
print("\n First Array  : \n" , array)


 First Array  : 
 [[148.    72.    35.   ...   0.63  50.     1.  ]
 [ 85.    66.    29.   ...   0.35  31.     0.  ]
 [183.    64.     0.   ...   0.67  32.     1.  ]
 ...
 [121.    72.    23.   ...   0.24  30.     0.  ]
 [126.    60.     0.   ...   0.35  47.     1.  ]
 [ 93.    70.    31.   ...   0.32  23.     0.  ]]


In [8]:
data_scaler  = StandardScaler().fit(array)
data_rescaled = data_scaler.transform(array)

In [9]:
set_printoptions(precision=2)
print("\n Rescaled Data : \n ", data_rescaled[0:5])


 Rescaled Data : 
  [[ 0.85  0.15  0.91 -0.69  0.2   0.47  1.43  1.37]
 [-1.12 -0.16  0.53 -0.69 -0.68 -0.37 -0.19 -0.73]
 [ 1.94 -0.26 -1.29 -0.69 -1.1   0.6  -0.11  1.37]
 [-1.   -0.16  0.15  0.12 -0.49 -0.92 -1.04 -0.73]
 [ 0.5  -1.5   0.91  0.77  1.41  5.48 -0.02  1.37]]
